address: "0.0.0.0"
port: 9123
metricsPath: "/metrics"
log:
  level: "debug"
  log_path: "/var/log/uos-exporter/node_process_exporter.log"
// Part 2 commit for node_process_exporter/config/node-process-exporter.yaml
