address: "0.0.0.0"
port: 9043
metricsPath: "/metrics"
log:
  level: "debug"
  log_path: "/var/log/uos-exporter/keepalived-container-exporter.log"
keepalived_json: false
keepalived_pid: "/var/run/keepalived.pid"
keepalived_check_script: ""
keepalived_container_name: ""
keepalived_container_tmp_dir: "/tmp/keepalived"
