address: "0.0.0.0"
port: 9040
metricsPath: "/metrics"
log:
  level: "debug"
  log_path: "/var/log/uos-exporter/keepalived-container-exporter.log"
url: "amqp://guest:guest@localhost"
executable: "/root/agent-exporter/tmp/rabbitmq_cli_consumer_exporter/internal/metrics/command.php"
configuration: "/root/agent-exporter/tmp/rabbitmq_cli_consumer_exporter/internal/metrics/example.conf"
pipe: false
strict_exit_code: false
no_declare: false
no_datetime: false
queue_name: ""
include_metadata: false
