address: "0.0.0.0"
port: 9019
metricsPath: "/metrics"
log:
  level: "info"
  log_path: "/var/log/uos-exporter/postgres-exporter.log"
  # level: "debug"
  # log_path: "./postgres-exporter.log"


instances:
  - name: "local"
    connection:
      host: "localhost"
      port: 5432
      user: "postgres"
      password: "postgres"
      dbname: "postgres"
      sslmode: "disable"