// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ClusterLabs/ha_cluster_exporter/collector (interfaces: ScrapeCollector)

// Package mock_collector is a generated GoMock package.
package mock_collector

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	prometheus "github.com/prometheus/client_golang/prometheus"
)

// MockScrapeCollector is a mock of ScrapeCollector interface.
type MockScrapeCollector struct {
	ctrl     *gomock.Controller
	recorder *MockScrapeCollectorMockRecorder
}

// MockScrapeCollectorMockRecorder is the mock recorder for MockScrapeCollector.
type MockScrapeCollectorMockRecorder struct {
	mock *MockScrapeCollector
}

// NewMockScrapeCollector creates a new mock instance.

// TODO: implement functions
