address: "0.0.0.0"
port: 9046
metricsPath: "/metrics"
log:
  level: "debug"
  log_path: "/var/log/uos-exporter/snmp-exporter.log"
snmp_config_file: "snmp.yaml"
snmp_concurrency: 1
snmp_debug: false
snmp_expand_env_vars: false